version: '3'

services:
  server:
    image: node:latest
    working_dir: /react
    volumes:
      - ./react:/react
    expose:
      - 3004
    ports:
      - "3004:3004"
    command: bash -c "npm install  && npm install npm@latest -g && npm audit fix --force && npm run srv-dev"
  client:
    image: node:latest
    working_dir: /react
    command:  bash -c "npm install  && npm install npm@latest -g && npm audit fix --force && npm run srv-dist"
    expose:
      - 8080
    ports:
      - "8080:8080"
    stdin_open: true
    volumes:
      - ./react:/react
